### ISSUE TITLE
*In need of CMD prompts please!*

### ISSUE THREAD

**Issue by goodfaith7** [wagrenier/PssMux#3]
I've downloaded the PSSMux tool and installed it to my system, but unfortunately I can't use it because I don't know what prompt to type in order to activate it. 
I checked all of the files and even opened the dependencies in notepad hoping to figure it out for myself, and while I did find nearly all of the other prompts in the text, I was unsuccessful in finding the initiation prompt/prefix.

Please, if you have the time, add a "readme.txt" or some kind of help file containing the activation prompt, or maybe even a YouTube tutorial. 

I appreciate your time, and look forward to using this tool soon! 

:)

**Comment by wagrenier** [comment]
.\PssMux.exe -h

**Comment by goodfaith7** [comment]
Thank you very much for supplying that prompt, but for some reason (even after specifying every single folder as a system environment variable), CMD still says it's an unrecognized command... I just want to make sure I've set it up correctly and that it indeed is supposed to run in CMD... I see Python scripts as well, does this mean I should use Python thru CMD to run it? Or is it just the classic CMD system variable setup?  Is there a specific folder I should place the "PssMux-main" folder inside of?
Sorry for so many questions, I'm just desperate to figure out what I've done wrong- thanks again in advance 🙏
________________________________

**Comment by wagrenier** [comment]
If you download the code and not the executable it won't work, just download the latest released executable. No need of env vars its just a typical cli tool. Unsure how I can help you beyond that. If you cannot use a cli I am pretty sure this tool is not meant for you.
